// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc6sm9EoC4MRPtzAYZEQKYBbnNFTSwsek',
    appId: '1:161476938145:android:17aee4854d857810b7e3e0',
    messagingSenderId: '161476938145',
    projectId: 'air-conditioning-system-debfa',
    databaseURL: 'https://air-conditioning-system-debfa-default-rtdb.firebaseio.com',
    storageBucket: 'air-conditioning-system-debfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1IYGg42l24RHl5DIEbpOpMcQiZccm_l0',
    appId: '1:161476938145:ios:4d19c5d0bfac515fb7e3e0',
    messagingSenderId: '161476938145',
    projectId: 'air-conditioning-system-debfa',
    databaseURL: 'https://air-conditioning-system-debfa-default-rtdb.firebaseio.com',
    storageBucket: 'air-conditioning-system-debfa.appspot.com',
    iosBundleId: 'com.example.airConditioningSystem',
  );
}
